### ISSUE TITLE
UT compatibility issue with GO 1.13.x

### ISSUE THREAD

**Issue by yangwwei** [apache/incubator-yunikorn-k8shim#53]
Seems like UT starts to fail on flag after upgrade GO to 1.13.x.

**Comment by wilfred-s** [comment]
This seems to be caused by us relying on undefined behaviour and fixes in the go language.

Calling `flag.Parse()` in an init is considered an incorrect behaviour.
This is part of the 1.13 release notes: https://tip.golang.org/doc/go1.13#testing

We currently call `flag.Parse()` in the init of the `SchedulerConf` which we need to change.

**Comment by yangwwei** [comment]
I think this is a lesson learned that not to use `init()` functions, the cost of convenience is some un-expected behaviors like this. I was thinking to remove these init functions and replace them with `sync.once`, does that make sense?

**Comment by wilfred-s** [comment]
I agree that `init()` functions could be problematic. However it is simpler than having to check in each location that the package is initialised. Using `sync.once` could add overhead or wrapping which we do not need. I think we need to look at a combination of the two: `init()` when we know it is package local initialisation only. If we have interaction with other packages or optional initialisation use the `sync.once`

This `flag.Parse()` is a case of interacting with multiple packages, I don't think we will have many more of these cases.

**Comment by wilfred-s** [comment]
moved to jira:
https://issues.apache.org/jira/browse/YUNIKORN-24
